repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-merge-conflict
      - id: check-ast
      - id: debug-statements
  - repo: https://github.com/seantis/pre-commit-hooks
    rev: v1.0.1
    hooks:
      - id: nocheckin
        exclude: .pre-commit-config.yaml
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear ==23.3.23
        files: '^src/.*\.py'
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.6
    hooks:
      - id: bandit
        additional_dependencies:
          - 'bandit[toml]'
        args: ['-r', 'src', '-c', 'pyproject.toml']
        always_run: true
        files: '^$'
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.1
    hooks:
      - id: mypy
        additional_dependencies:
          - cryptography==41.0.7
          - discord.py==2.3.2
          - 'psycopg[c]==3.1.15'
          - psycopg-pool==3.2.0
          - pydantic==2.5.2
          - pydantic-core==2.14.5
          - pydantic-settings==2.1.0
          - types-gevent==23.9.0.1
          - types-greenlet==3.0.0.0
          - types-oauthlib==3.2.0.10
          - types-psutil==5.9.5.17
          - types-pyOpenSSL==23.3.0.0
          - types-pyYAML==6.0.12.12
          - types-redis==4.6.0.11
          - types-requests==2.31.0.10
          - types-requests-oauthlib==1.3.0.1
          - types-uWSGI==2.0.0.1
          - urllib3==2.1.0
        args: ['-p', 'turbo_sticks', '-p', 'turbo_sticks_scripts']
        always_run: true
        files: '^$'
