repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-merge-conflict
      - id: check-ast
      - id: debug-statements
  - repo: https://github.com/seantis/pre-commit-hooks
    rev: v1.0.1
    hooks:
      - id: nocheckin
        exclude: .pre-commit-config.yaml
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear ==24.2.6
        files: '^src/.*\.py'
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.7
    hooks:
      - id: bandit
        additional_dependencies:
          - 'bandit[toml]'
        args: ['-r', 'src', '-c', 'pyproject.toml']
        always_run: true
        files: '^$'
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.1
    hooks:
      - id: mypy
        additional_dependencies:
          - cryptography==42.0.5
          - discord.py==2.3.2
          - 'psycopg[c]==3.1.17'
          - psycopg-pool==3.2.1
          - pydantic==2.6.3
          - pydantic-core==2.16.3
          - pydantic-settings==2.2.1
          - types-gevent==24.2.0.20240301
          - types-greenlet==3.0.0.20240106
          - types-oauthlib==3.2.0.20240217
          - types-psutil==5.9.5.20240205
          - types-pyOpenSSL==24.0.0.20240228
          - types-pyYAML==6.0.12.12
          - types-redis==4.6.0.20240218
          - types-requests==2.31.0.20240218
          - types-requests-oauthlib==1.3.0.20240106
          - types-uWSGI==2.0.0.20240106
          - urllib3==2.2.1
        args: ['-p', 'turbo_sticks', '-p', 'turbo_sticks_scripts']
        always_run: true
        files: '^$'
