repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-merge-conflict
      - id: check-ast
      - id: debug-statements
  - repo: https://github.com/seantis/pre-commit-hooks
    rev: v1.0.1
    hooks:
      - id: nocheckin
        exclude: .pre-commit-config.yaml
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        files: '^src/.*\.py'
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        additional_dependencies: [toml]
        args: ['-c', 'pyproject.toml']
        files: '^src/.*\.py'
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        additional_dependencies:
          - discord.py==2.1.0
          - gevent==22.10.2
          - oauthlib==3.2.2
          - redis==4.4.0
          - requests==2.28.1
          - requests-oauthlib==1.3.1
          - 'psycopg[c]==3.1.7'
          - 'psycopg-pool==3.1.5'
          - pydantic==1.10.2
          - types-cryptography==3.3.23.2
          - types-oauthlib==3.2.0.1
          - types-pyYAML==6.0.12.2
          - types-redis==4.3.21.6
          - types-requests==2.28.11.7
        args: ['-p', 'turbo_sticks']
        always_run: true
        files: '^$'
