repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-merge-conflict
      - id: check-ast
      - id: debug-statements
  - repo: https://github.com/seantis/pre-commit-hooks
    rev: v1.1.0
    hooks:
      - id: nocheckin
        exclude: .pre-commit-config.yaml
  - repo: https://github.com/PyCQA/flake8
    rev: 7.2.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear ==24.12.12
        files: '^src/.*\.py'
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.3
    hooks:
      - id: bandit
        additional_dependencies:
          - 'bandit[toml]'
        args: ['-r', 'src', '-c', 'pyproject.toml']
        always_run: true
        files: '^$'
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        additional_dependencies:
          - cryptography==44.0.2
          - discord.py==2.5.2
          - 'psycopg[c]==3.2.6'
          - psycopg-pool==3.2.6
          - pydantic==2.11.3
          - pydantic-core==2.33.1
          - pydantic-settings==2.9.1
          - types-cffi==1.17.0.20250326
          - types-gevent==24.11.0.20250401
          - types-greenlet==3.2.0.20250417
          - types-oauthlib==3.2.0.20250408
          - types-psutil==7.0.0.20250401
          - types-pyopenssl==24.1.0.20240722
          - types-pyyaml==6.0.12.20250402
          - types-redis==4.6.0.20241004
          - types-requests==2.32.0.20250328
          - types-requests-oauthlib==2.0.0.20250306
          - types-setuptools==79.0.0.20250422
          - types-uwsgi==2.0.0.20240516
          - urllib3==2.4.0
        args: ['-p', 'turbo_sticks', '-p', 'turbo_sticks_scripts']
        always_run: true
        files: '^$'
