repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-merge-conflict
      - id: check-ast
      - id: debug-statements
  - repo: https://github.com/seantis/pre-commit-hooks
    rev: v1.0.1
    hooks:
      - id: nocheckin
        exclude: .pre-commit-config.yaml
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear ==23.3.23
        files: '^src/.*\.py'
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        additional_dependencies:
          - 'bandit[toml]'
        args: ['-r', 'src', '-c', 'pyproject.toml']
        always_run: true
        files: '^$'
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.2.0
    hooks:
      - id: mypy
        additional_dependencies:
          - discord.py==2.2.2
          - 'psycopg[c]==3.1.8'
          - psycopg-pool==3.1.7
          - pydantic==1.10.7
          - types-oauthlib==3.2.0.7
          - types-pyYAML==6.0.12.9
          - types-redis==4.5.4.1
          - types-requests==2.29.0.0
        args: ['-p', 'turbo_sticks']
        always_run: true
        files: '^$'
